# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jiamin/Desktop/Develop/Python/Program/TestUI/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1181, 764)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1181, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_1.sizePolicy().hasHeightForWidth())
        self.tab_1.setSizePolicy(sizePolicy)
        self.tab_1.setObjectName("tab_1")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout.setContentsMargins(11, 0, 11, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.group1 = QtWidgets.QGroupBox(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group1.sizePolicy().hasHeightForWidth())
        self.group1.setSizePolicy(sizePolicy)
        self.group1.setMaximumSize(QtCore.QSize(10000, 10000))
        self.group1.setStyleSheet("")
        self.group1.setTitle("")
        self.group1.setObjectName("group1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.group1)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lb_state = QtWidgets.QLabel(self.group1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_state.sizePolicy().hasHeightForWidth())
        self.lb_state.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lb_state.setFont(font)
        self.lb_state.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_state.setObjectName("lb_state")
        self.verticalLayout_3.addWidget(self.lb_state)
        self.lb_time = QtWidgets.QLabel(self.group1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_time.sizePolicy().hasHeightForWidth())
        self.lb_time.setSizePolicy(sizePolicy)
        self.lb_time.setObjectName("lb_time")
        self.verticalLayout_3.addWidget(self.lb_time)
        self.le_time = QtWidgets.QLineEdit(self.group1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_time.sizePolicy().hasHeightForWidth())
        self.le_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_time.setFont(font)
        self.le_time.setReadOnly(True)
        self.le_time.setObjectName("le_time")
        self.verticalLayout_3.addWidget(self.le_time)
        self.lb_total = QtWidgets.QLabel(self.group1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_total.sizePolicy().hasHeightForWidth())
        self.lb_total.setSizePolicy(sizePolicy)
        self.lb_total.setObjectName("lb_total")
        self.verticalLayout_3.addWidget(self.lb_total)
        self.le_total = QtWidgets.QLineEdit(self.group1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_total.sizePolicy().hasHeightForWidth())
        self.le_total.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_total.setFont(font)
        self.le_total.setReadOnly(True)
        self.le_total.setObjectName("le_total")
        self.verticalLayout_3.addWidget(self.le_total)
        self.lb_pass = QtWidgets.QLabel(self.group1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_pass.sizePolicy().hasHeightForWidth())
        self.lb_pass.setSizePolicy(sizePolicy)
        self.lb_pass.setObjectName("lb_pass")
        self.verticalLayout_3.addWidget(self.lb_pass)
        self.le_pass = QtWidgets.QLineEdit(self.group1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_pass.sizePolicy().hasHeightForWidth())
        self.le_pass.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_pass.setFont(font)
        self.le_pass.setReadOnly(True)
        self.le_pass.setObjectName("le_pass")
        self.verticalLayout_3.addWidget(self.le_pass)
        self.lb_yield = QtWidgets.QLabel(self.group1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_yield.sizePolicy().hasHeightForWidth())
        self.lb_yield.setSizePolicy(sizePolicy)
        self.lb_yield.setObjectName("lb_yield")
        self.verticalLayout_3.addWidget(self.lb_yield)
        self.le_yield = QtWidgets.QLineEdit(self.group1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_yield.sizePolicy().hasHeightForWidth())
        self.le_yield.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_yield.setFont(font)
        self.le_yield.setReadOnly(True)
        self.le_yield.setObjectName("le_yield")
        self.verticalLayout_3.addWidget(self.le_yield)
        self.gridLayout.addWidget(self.group1, 0, 2, 1, 1)
        self.group2 = QtWidgets.QGroupBox(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group2.sizePolicy().hasHeightForWidth())
        self.group2.setSizePolicy(sizePolicy)
        self.group2.setMaximumSize(QtCore.QSize(10000, 10000))
        self.group2.setStyleSheet("")
        self.group2.setTitle("")
        self.group2.setObjectName("group2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.group2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_state2 = QtWidgets.QLabel(self.group2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lb_state2.setFont(font)
        self.lb_state2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_state2.setObjectName("lb_state2")
        self.verticalLayout_2.addWidget(self.lb_state2)
        self.lb_time_3 = QtWidgets.QLabel(self.group2)
        self.lb_time_3.setObjectName("lb_time_3")
        self.verticalLayout_2.addWidget(self.lb_time_3)
        self.le_time2 = QtWidgets.QLineEdit(self.group2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_time2.setFont(font)
        self.le_time2.setReadOnly(True)
        self.le_time2.setObjectName("le_time2")
        self.verticalLayout_2.addWidget(self.le_time2)
        self.lb_total_3 = QtWidgets.QLabel(self.group2)
        self.lb_total_3.setObjectName("lb_total_3")
        self.verticalLayout_2.addWidget(self.lb_total_3)
        self.le_total2 = QtWidgets.QLineEdit(self.group2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_total2.setFont(font)
        self.le_total2.setReadOnly(True)
        self.le_total2.setObjectName("le_total2")
        self.verticalLayout_2.addWidget(self.le_total2)
        self.lb_pass_3 = QtWidgets.QLabel(self.group2)
        self.lb_pass_3.setStyleSheet("")
        self.lb_pass_3.setObjectName("lb_pass_3")
        self.verticalLayout_2.addWidget(self.lb_pass_3)
        self.le_pass2 = QtWidgets.QLineEdit(self.group2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_pass2.setFont(font)
        self.le_pass2.setReadOnly(True)
        self.le_pass2.setObjectName("le_pass2")
        self.verticalLayout_2.addWidget(self.le_pass2)
        self.lb_yield_3 = QtWidgets.QLabel(self.group2)
        self.lb_yield_3.setObjectName("lb_yield_3")
        self.verticalLayout_2.addWidget(self.lb_yield_3)
        self.le_yield2 = QtWidgets.QLineEdit(self.group2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_yield2.setFont(font)
        self.le_yield2.setReadOnly(True)
        self.le_yield2.setObjectName("le_yield2")
        self.verticalLayout_2.addWidget(self.le_yield2)
        self.gridLayout.addWidget(self.group2, 1, 2, 1, 1)
        self.lb_space2 = QtWidgets.QLabel(self.tab_1)
        self.lb_space2.setText("")
        self.lb_space2.setObjectName("lb_space2")
        self.gridLayout.addWidget(self.lb_space2, 2, 2, 1, 1)
        self.testlist2 = QtWidgets.QTreeWidget(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.testlist2.setFont(font)
        self.testlist2.setStyleSheet("gridline-color: rgb(149, 150, 255);")
        self.testlist2.setObjectName("testlist2")
        self.testlist2.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.testlist2, 0, 1, 4, 1)
        self.testlist = QtWidgets.QTreeWidget(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.testlist.setFont(font)
        self.testlist.setStyleSheet("")
        self.testlist.setObjectName("testlist")
        self.testlist.headerItem().setText(0, "1")
        self.testlist.header().setHighlightSections(True)
        self.gridLayout.addWidget(self.testlist, 0, 0, 4, 1)
        self.btn_group = QtWidgets.QGroupBox(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_group.sizePolicy().hasHeightForWidth())
        self.btn_group.setSizePolicy(sizePolicy)
        self.btn_group.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.btn_group.setTitle("")
        self.btn_group.setObjectName("btn_group")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.btn_group)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_start = QtWidgets.QPushButton(self.btn_group)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_start.setFont(font)
        self.btn_start.setStyleSheet("")
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout_4.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(self.btn_group)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_stop.setFont(font)
        self.btn_stop.setObjectName("btn_stop")
        self.verticalLayout_4.addWidget(self.btn_stop)
        self.gridLayout.addWidget(self.btn_group, 5, 2, 1, 1)
        self.lb_space3 = QtWidgets.QLabel(self.tab_1)
        self.lb_space3.setText("")
        self.lb_space3.setObjectName("lb_space3")
        self.gridLayout.addWidget(self.lb_space3, 3, 2, 2, 1)
        self.pbar = QtWidgets.QProgressBar(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbar.sizePolicy().hasHeightForWidth())
        self.pbar.setSizePolicy(sizePolicy)
        self.pbar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbar.setMaximum(10000)
        self.pbar.setProperty("value", -1)
        self.pbar.setTextVisible(False)
        self.pbar.setObjectName("pbar")
        self.gridLayout.addWidget(self.pbar, 4, 0, 1, 1)
        self.pbar2 = QtWidgets.QProgressBar(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbar2.sizePolicy().hasHeightForWidth())
        self.pbar2.setSizePolicy(sizePolicy)
        self.pbar2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbar2.setMaximum(10000)
        self.pbar2.setProperty("value", -1)
        self.pbar2.setTextVisible(False)
        self.pbar2.setObjectName("pbar2")
        self.gridLayout.addWidget(self.pbar2, 4, 1, 1, 1)
        self.te_log = QtWidgets.QTextEdit(self.tab_1)
        self.te_log.setMinimumSize(QtCore.QSize(0, 70))
        self.te_log.setMaximumSize(QtCore.QSize(1000000, 500))
        self.te_log.setObjectName("te_log")
        self.gridLayout.addWidget(self.te_log, 5, 0, 1, 2)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setContentsMargins(12, 0, 12, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lb_edit = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lb_edit.setFont(font)
        self.lb_edit.setObjectName("lb_edit")
        self.gridLayout_2.addWidget(self.lb_edit, 1, 0, 1, 1)
        self.btn_saveseq = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_saveseq.setFont(font)
        self.btn_saveseq.setObjectName("btn_saveseq")
        self.gridLayout_2.addWidget(self.btn_saveseq, 1, 2, 1, 1)
        self.cb_seq = QtWidgets.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_seq.setFont(font)
        self.cb_seq.setObjectName("cb_seq")
        self.cb_seq.addItem("")
        self.cb_seq.addItem("")
        self.gridLayout_2.addWidget(self.cb_seq, 1, 1, 1, 1)
        self.tableseq = QtWidgets.QTableWidget(self.tab_2)
        self.tableseq.setObjectName("tableseq")
        self.tableseq.setColumnCount(0)
        self.tableseq.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableseq, 2, 0, 2, 3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_3.sizePolicy().hasHeightForWidth())
        self.tab_3.setSizePolicy(sizePolicy)
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setContentsMargins(12, 0, 12, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setHorizontalSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gb_moto = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_moto.sizePolicy().hasHeightForWidth())
        self.gb_moto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gb_moto.setFont(font)
        self.gb_moto.setTitle("")
        self.gb_moto.setObjectName("gb_moto")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gb_moto)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dsb_speed = QtWidgets.QDoubleSpinBox(self.gb_moto)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dsb_speed.setFont(font)
        self.dsb_speed.setMaximum(10000.0)
        self.dsb_speed.setObjectName("dsb_speed")
        self.gridLayout_3.addWidget(self.dsb_speed, 1, 1, 1, 1)
        self.pb_reset = QtWidgets.QPushButton(self.gb_moto)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_reset.setFont(font)
        self.pb_reset.setObjectName("pb_reset")
        self.gridLayout_3.addWidget(self.pb_reset, 4, 0, 1, 1)
        self.pb_stop = QtWidgets.QPushButton(self.gb_moto)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_stop.setFont(font)
        self.pb_stop.setObjectName("pb_stop")
        self.gridLayout_3.addWidget(self.pb_stop, 4, 1, 1, 1)
        self.dsb_real_pos = QtWidgets.QDoubleSpinBox(self.gb_moto)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dsb_real_pos.setFont(font)
        self.dsb_real_pos.setMaximum(10000.0)
        self.dsb_real_pos.setObjectName("dsb_real_pos")
        self.gridLayout_3.addWidget(self.dsb_real_pos, 0, 1, 1, 1)
        self.pb_jog1 = QtWidgets.QPushButton(self.gb_moto)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_jog1.setFont(font)
        self.pb_jog1.setObjectName("pb_jog1")
        self.gridLayout_3.addWidget(self.pb_jog1, 0, 2, 1, 1)
        self.cb_limitp = QtWidgets.QCheckBox(self.gb_moto)
        self.cb_limitp.setObjectName("cb_limitp")
        self.gridLayout_3.addWidget(self.cb_limitp, 5, 2, 1, 1)
        self.pb_jog2 = QtWidgets.QPushButton(self.gb_moto)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_jog2.setFont(font)
        self.pb_jog2.setObjectName("pb_jog2")
        self.gridLayout_3.addWidget(self.pb_jog2, 1, 2, 1, 1)
        self.dsb_step = QtWidgets.QDoubleSpinBox(self.gb_moto)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dsb_step.setFont(font)
        self.dsb_step.setMaximum(10000.0)
        self.dsb_step.setObjectName("dsb_step")
        self.gridLayout_3.addWidget(self.dsb_step, 3, 1, 1, 1)
        self.lb_step = QtWidgets.QLabel(self.gb_moto)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_step.setFont(font)
        self.lb_step.setObjectName("lb_step")
        self.gridLayout_3.addWidget(self.lb_step, 3, 0, 1, 1)
        self.lb_speed = QtWidgets.QLabel(self.gb_moto)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_speed.setFont(font)
        self.lb_speed.setObjectName("lb_speed")
        self.gridLayout_3.addWidget(self.lb_speed, 1, 0, 1, 1)
        self.lb_speed_2 = QtWidgets.QLabel(self.gb_moto)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_speed_2.setFont(font)
        self.lb_speed_2.setObjectName("lb_speed_2")
        self.gridLayout_3.addWidget(self.lb_speed_2, 0, 0, 1, 1)
        self.cb_zero = QtWidgets.QCheckBox(self.gb_moto)
        self.cb_zero.setObjectName("cb_zero")
        self.gridLayout_3.addWidget(self.cb_zero, 5, 0, 1, 1)
        self.cb_limitm = QtWidgets.QCheckBox(self.gb_moto)
        self.cb_limitm.setObjectName("cb_limitm")
        self.gridLayout_3.addWidget(self.cb_limitm, 5, 1, 1, 1)
        self.pb_absolute = QtWidgets.QPushButton(self.gb_moto)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_absolute.setFont(font)
        self.pb_absolute.setObjectName("pb_absolute")
        self.gridLayout_3.addWidget(self.pb_absolute, 3, 2, 1, 1)
        self.pb_relative = QtWidgets.QPushButton(self.gb_moto)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_relative.setFont(font)
        self.pb_relative.setObjectName("pb_relative")
        self.gridLayout_3.addWidget(self.pb_relative, 4, 2, 1, 1)
        self.gridLayout_5.addWidget(self.gb_moto, 2, 0, 1, 1)
        self.lb_axis = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_axis.sizePolicy().hasHeightForWidth())
        self.lb_axis.setSizePolicy(sizePolicy)
        self.lb_axis.setMaximumSize(QtCore.QSize(16777215, 10000))
        self.lb_axis.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lb_axis.setObjectName("lb_axis")
        self.gridLayout_5.addWidget(self.lb_axis, 0, 0, 1, 1)
        self.cb_axis = QtWidgets.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_axis.setFont(font)
        self.cb_axis.setMaxVisibleItems(10)
        self.cb_axis.setObjectName("cb_axis")
        self.gridLayout_5.addWidget(self.cb_axis, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_io = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_io.sizePolicy().hasHeightForWidth())
        self.lb_io.setSizePolicy(sizePolicy)
        self.lb_io.setMaximumSize(QtCore.QSize(16777215, 10000))
        self.lb_io.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lb_io.setObjectName("lb_io")
        self.verticalLayout.addWidget(self.lb_io)
        self.tw_io = QtWidgets.QTableWidget(self.tab_3)
        self.tw_io.setObjectName("tw_io")
        self.tw_io.setColumnCount(0)
        self.tw_io.setRowCount(0)
        self.verticalLayout.addWidget(self.tw_io)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_9.setContentsMargins(11, 0, 11, 0)
        self.gridLayout_9.setHorizontalSpacing(100)
        self.gridLayout_9.setVerticalSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lb_image = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_image.sizePolicy().hasHeightForWidth())
        self.lb_image.setSizePolicy(sizePolicy)
        self.lb_image.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lb_image.setText("")
        self.lb_image.setScaledContents(False)
        self.lb_image.setObjectName("lb_image")
        self.gridLayout_9.addWidget(self.lb_image, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(20)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lb_camera = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_camera.setFont(font)
        self.lb_camera.setObjectName("lb_camera")
        self.gridLayout_8.addWidget(self.lb_camera, 2, 0, 1, 1)
        self.cb_camera = QtWidgets.QComboBox(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cb_camera.setFont(font)
        self.cb_camera.setObjectName("cb_camera")
        self.gridLayout_8.addWidget(self.cb_camera, 2, 1, 1, 1)
        self.lb_extime = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_extime.setFont(font)
        self.lb_extime.setObjectName("lb_extime")
        self.gridLayout_8.addWidget(self.lb_extime, 3, 0, 1, 1)
        self.lb_space1 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_space1.sizePolicy().hasHeightForWidth())
        self.lb_space1.setSizePolicy(sizePolicy)
        self.lb_space1.setText("")
        self.lb_space1.setObjectName("lb_space1")
        self.gridLayout_8.addWidget(self.lb_space1, 4, 0, 1, 1)
        self.pb_opencamera = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_opencamera.sizePolicy().hasHeightForWidth())
        self.pb_opencamera.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_opencamera.setFont(font)
        self.pb_opencamera.setObjectName("pb_opencamera")
        self.gridLayout_8.addWidget(self.pb_opencamera, 5, 0, 1, 1)
        self.pb_loadimg = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_loadimg.sizePolicy().hasHeightForWidth())
        self.pb_loadimg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_loadimg.setFont(font)
        self.pb_loadimg.setObjectName("pb_loadimg")
        self.gridLayout_8.addWidget(self.pb_loadimg, 5, 1, 1, 1)
        self.pb_live = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_live.sizePolicy().hasHeightForWidth())
        self.pb_live.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_live.setFont(font)
        self.pb_live.setObjectName("pb_live")
        self.gridLayout_8.addWidget(self.pb_live, 6, 0, 1, 1)
        self.pb_snap = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_snap.sizePolicy().hasHeightForWidth())
        self.pb_snap.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_snap.setFont(font)
        self.pb_snap.setObjectName("pb_snap")
        self.gridLayout_8.addWidget(self.pb_snap, 6, 1, 1, 1)
        self.sb_extime = QtWidgets.QSpinBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_extime.sizePolicy().hasHeightForWidth())
        self.sb_extime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_extime.setFont(font)
        self.sb_extime.setObjectName("sb_extime")
        self.gridLayout_8.addWidget(self.sb_extime, 3, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_4.addWidget(self.tabWidget, 6, 0, 1, 1)
        self.le_main_user = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_main_user.setFont(font)
        self.le_main_user.setStyleSheet("")
        self.le_main_user.setReadOnly(True)
        self.le_main_user.setObjectName("le_main_user")
        self.gridLayout_4.addWidget(self.le_main_user, 5, 0, 1, 1)
        self.lb_title = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lb_title.setFont(font)
        self.lb_title.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 150), stop:1 rgba(0, 0, 0, 0));\n"
"")
        self.lb_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_title.setObjectName("lb_title")
        self.gridLayout_4.addWidget(self.lb_title, 1, 0, 1, 1)
        self.lb_ver = QtWidgets.QLabel(self.centralWidget)
        self.lb_ver.setObjectName("lb_ver")
        self.gridLayout_4.addWidget(self.lb_ver, 7, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1181, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuUser = QtWidgets.QMenu(self.menuBar)
        self.menuUser.setObjectName("menuUser")
        self.menuTool = QtWidgets.QMenu(self.menuBar)
        self.menuTool.setObjectName("menuTool")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolBar.setFont(font)
        self.toolBar.setStyleSheet("border-style: flat;\n"
"border-bottom: 1px solid rgb(142, 142, 142);")
        self.toolBar.setIconSize(QtCore.QSize(20, 20))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionReload_CSV = QtWidgets.QAction(MainWindow)
        self.actionReload_CSV.setObjectName("actionReload_CSV")
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionLoop_Test = QtWidgets.QAction(MainWindow)
        self.actionLoop_Test.setObjectName("actionLoop_Test")
        self.actionMain_Window = QtWidgets.QAction(MainWindow)
        self.actionMain_Window.setCheckable(False)
        self.actionMain_Window.setObjectName("actionMain_Window")
        self.actionEdit_Window = QtWidgets.QAction(MainWindow)
        self.actionEdit_Window.setObjectName("actionEdit_Window")
        self.actionEdit_Sequence = QtWidgets.QAction(MainWindow)
        self.actionEdit_Sequence.setObjectName("actionEdit_Sequence")
        self.actionZmq_Debug = QtWidgets.QAction(MainWindow)
        self.actionZmq_Debug.setObjectName("actionZmq_Debug")
        self.actionTcp_Debug = QtWidgets.QAction(MainWindow)
        self.actionTcp_Debug.setObjectName("actionTcp_Debug")
        self.actionMotion_Debug = QtWidgets.QAction(MainWindow)
        self.actionMotion_Debug.setObjectName("actionMotion_Debug")
        self.actionSerial_Debug = QtWidgets.QAction(MainWindow)
        self.actionSerial_Debug.setObjectName("actionSerial_Debug")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionStart.setFont(font)
        self.actionStart.setVisible(True)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionEdit.setFont(font)
        self.actionEdit.setObjectName("actionEdit")
        self.actionLoginTool = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionLoginTool.setFont(font)
        self.actionLoginTool.setObjectName("actionLoginTool")
        self.actionAutomation = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionAutomation.setFont(font)
        self.actionAutomation.setObjectName("actionAutomation")
        self.actionMainwindow = QtWidgets.QAction(MainWindow)
        self.actionMainwindow.setObjectName("actionMainwindow")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setObjectName("actionPause")
        self.actionContinue = QtWidgets.QAction(MainWindow)
        self.actionContinue.setObjectName("actionContinue")
        self.actionToolBar = QtWidgets.QAction(MainWindow)
        self.actionToolBar.setCheckable(True)
        self.actionToolBar.setChecked(True)
        self.actionToolBar.setObjectName("actionToolBar")
        self.actionReload_Scripts = QtWidgets.QAction(MainWindow)
        self.actionReload_Scripts.setObjectName("actionReload_Scripts")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionVision_Window = QtWidgets.QAction(MainWindow)
        self.actionVision_Window.setObjectName("actionVision_Window")
        self.menuFile.addAction(self.actionReload_Scripts)
        self.menuFile.addAction(self.actionReload_CSV)
        self.menuFile.addAction(self.actionEdit_Sequence)
        self.menuUser.addAction(self.actionLogin)
        self.menuTool.addAction(self.actionZmq_Debug)
        self.menuTool.addAction(self.actionTcp_Debug)
        self.menuTool.addAction(self.actionSerial_Debug)
        self.menuTool.addAction(self.actionMotion_Debug)
        self.menuView.addAction(self.actionMain_Window)
        self.menuView.addAction(self.actionEdit_Window)
        self.menuView.addAction(self.actionVision_Window)
        self.menuView.addAction(self.actionToolBar)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuUser.menuAction())
        self.menuBar.addAction(self.menuTool.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMainwindow)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionContinue)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLoginTool)
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionAutomation)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PlatForm"))
        self.lb_state.setText(_translate("MainWindow", "Testing"))
        self.lb_time.setText(_translate("MainWindow", "TestTime:"))
        self.lb_total.setText(_translate("MainWindow", "Total:"))
        self.lb_pass.setText(_translate("MainWindow", "Pass:"))
        self.lb_yield.setText(_translate("MainWindow", "Yield:"))
        self.lb_state2.setText(_translate("MainWindow", "Testing"))
        self.lb_time_3.setText(_translate("MainWindow", "TestTime:"))
        self.lb_total_3.setText(_translate("MainWindow", "Total:"))
        self.lb_pass_3.setText(_translate("MainWindow", "Pass:"))
        self.lb_yield_3.setText(_translate("MainWindow", "Yield:"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Tab 1"))
        self.lb_edit.setText(_translate("MainWindow", "Edit Test Sequence"))
        self.btn_saveseq.setText(_translate("MainWindow", "Save"))
        self.cb_seq.setItemText(0, _translate("MainWindow", "Sequence1"))
        self.cb_seq.setItemText(1, _translate("MainWindow", "Sequence2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.pb_reset.setText(_translate("MainWindow", "Reset"))
        self.pb_stop.setText(_translate("MainWindow", "Stop"))
        self.pb_jog1.setText(_translate("MainWindow", "Jog+"))
        self.cb_limitp.setText(_translate("MainWindow", "Limit+"))
        self.pb_jog2.setText(_translate("MainWindow", "Jog-"))
        self.lb_step.setText(_translate("MainWindow", "Distance:"))
        self.lb_speed.setText(_translate("MainWindow", "Manual Speed:"))
        self.lb_speed_2.setText(_translate("MainWindow", "Current Position:"))
        self.cb_zero.setText(_translate("MainWindow", "Zero"))
        self.cb_limitm.setText(_translate("MainWindow", "Limit-"))
        self.pb_absolute.setText(_translate("MainWindow", "Absolute"))
        self.pb_relative.setText(_translate("MainWindow", "Relative"))
        self.lb_axis.setText(_translate("MainWindow", "Axis Name："))
        self.lb_io.setText(_translate("MainWindow", "IO Setting:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 3"))
        self.lb_camera.setText(_translate("MainWindow", "Camera:"))
        self.lb_extime.setText(_translate("MainWindow", "Exposure Time:"))
        self.pb_opencamera.setText(_translate("MainWindow", "Open"))
        self.pb_loadimg.setText(_translate("MainWindow", "Load"))
        self.pb_live.setText(_translate("MainWindow", "Live"))
        self.pb_snap.setText(_translate("MainWindow", "Snap"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 4"))
        self.lb_title.setText(_translate("MainWindow", "PyQt Software Platform Project"))
        self.lb_ver.setText(_translate("MainWindow", "V 1.0.0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuUser.setTitle(_translate("MainWindow", "User"))
        self.menuTool.setTitle(_translate("MainWindow", "Tool"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionReload_CSV.setText(_translate("MainWindow", "Reload Sequence"))
        self.actionReload_CSV.setToolTip(_translate("MainWindow", "Reload sequence"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionLogin.setToolTip(_translate("MainWindow", "Login system"))
        self.actionLoop_Test.setText(_translate("MainWindow", "Loop Test"))
        self.actionLoop_Test.setToolTip(_translate("MainWindow", "Loop test"))
        self.actionMain_Window.setText(_translate("MainWindow", "Main Window"))
        self.actionMain_Window.setToolTip(_translate("MainWindow", "Switch to main window"))
        self.actionEdit_Window.setText(_translate("MainWindow", "Edit Window"))
        self.actionEdit_Window.setToolTip(_translate("MainWindow", "Switch to edit window"))
        self.actionEdit_Sequence.setText(_translate("MainWindow", "Edit Sequence"))
        self.actionEdit_Sequence.setToolTip(_translate("MainWindow", "Edit sequence"))
        self.actionZmq_Debug.setText(_translate("MainWindow", "Zmq Debug"))
        self.actionZmq_Debug.setToolTip(_translate("MainWindow", "Zmq debug"))
        self.actionTcp_Debug.setText(_translate("MainWindow", "Tcp Debug"))
        self.actionTcp_Debug.setToolTip(_translate("MainWindow", "Tcp debug"))
        self.actionMotion_Debug.setText(_translate("MainWindow", "Motion Debug"))
        self.actionMotion_Debug.setToolTip(_translate("MainWindow", "Motion debug"))
        self.actionSerial_Debug.setText(_translate("MainWindow", "Serial Debug"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStart.setToolTip(_translate("MainWindow", "Start test"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStop.setToolTip(_translate("MainWindow", "Stop test"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionEdit.setToolTip(_translate("MainWindow", "Edit sequence"))
        self.actionLoginTool.setText(_translate("MainWindow", "Login"))
        self.actionLoginTool.setToolTip(_translate("MainWindow", "Login system"))
        self.actionAutomation.setText(_translate("MainWindow", "Automation"))
        self.actionAutomation.setToolTip(_translate("MainWindow", "Automation debug"))
        self.actionMainwindow.setText(_translate("MainWindow", "Mainwindow"))
        self.actionMainwindow.setToolTip(_translate("MainWindow", "Switch to main window"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionPause.setToolTip(_translate("MainWindow", "Pause test"))
        self.actionContinue.setText(_translate("MainWindow", "Continue"))
        self.actionContinue.setToolTip(_translate("MainWindow", "Continue test"))
        self.actionToolBar.setText(_translate("MainWindow", "ToolBar"))
        self.actionReload_Scripts.setText(_translate("MainWindow", "Reload Scripts"))
        self.actionReload_Scripts.setToolTip(_translate("MainWindow", "Reload scripts"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionRefresh.setToolTip(_translate("MainWindow", "Refresh scripts"))
        self.actionVision_Window.setText(_translate("MainWindow", "Vision Window"))

